#!/bin/bash

cd $OPENSHIFT_REPO_DIR

source /.openshift/bash_init.sh

nohup java -jar -Dspring.profiles.active=openshift -Dserver.port=${OPENSHIFT_DIY_PORT} -Dserver.address=${OPENSHIFT_DIY_IP} /target/*.jar 2>&1 &


