#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

PID=$(ps -ef | grep java.*\.jar | grep -v grep | awk '{ print $2 }')

if [ -z "$PID" ]
then
    echo $PID "Application is already stopped"
else
    kill $PID ; echo $PID "Application has been stopped"
fi

